from tkinter import *
import mysql.connector
class Main:
    def __init__(self):
        self.a = Tk()
        self.a.title('STUDENT')
        self.a.geometry('900x600')
        self.a.resizable(0,0)
        self.a.config(bg='#17abc2')
        self.db = mysql.connector.connect(
            host='localhost',
            user='root',
            password='',
            database = 'st')
        self.cursor = self.db.cursor()
    def btn(self):
        a=self.a
        f = Frame(a,height=500,width=200,bg='white')
        f.place(x=20,y=50)
        add = Button(f,text='ADDSTUDENT',fg='white',command=self.add,bg='#17abc2',font=('Times New Roman',16,'bold'),pady=14,activebackground='#f2da00',relief='ridge',cursor='hand2')
        add.place(x=20,y=20)
        update = Button(f,text='UPDATE',command=self.update,fg='white',bg='#17abc2',font=('Times New Roman',16,'bold'),padx=29,pady=12,activebackground='#f2da00',relief='ridge',cursor='hand2')
        update.place(x=20,y=100)
        delete = Button(f,text='DELETE',command=self.delete,fg='white',bg='#17abc2',font=('Times New Roman',16,'bold'),padx=30,pady=14,activebackground='#f2da00',relief='ridge',cursor='hand2')
        delete.place(x=20,y=180)
        show = Button(f,text='SHOW',command=self.show,fg='white',bg='#17abc2',font=('Times New Roman',16,'bold'),padx=40,pady=14,activebackground='#f2da00',relief='ridge',cursor='hand2')
        show.place(x=20,y=260)
        clr = Button(f,text='CLEAR',command=self.clear,fg='white',bg='#17abc2',font=('Times New Roman',16,'bold'),padx=36,pady=14,activebackground='#f2da00',relief='ridge',cursor='hand2')
        clr.place(x=20,y=340)
        exi = Button(f,text='EXIT',command=self.a.destroy,fg='white',bg='#17abc2',font=('Times New Roman',16,'bold'),padx=48,pady=10,activebackground='#f2da00',relief='ridge',cursor='hand2')
        exi.place(x=20,y=420)
    def add(self):
        a = self.a
        fr=Frame(a,height=500,width=620,bg='white')
        fr.place(x=250,y=50)
        f = Frame(fr,height=450,width=570,bg='#17abc2')
        f.place(x=25,y=25)
        Label(f,text='ADD STUDENT DETAILS',font=('Times New Roman',30,'bold'),bg='#17abc2',fg='white').place(x=40,y=10)
        Label(f,text='StudentNumber',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=10,y=80)
        Label(f,text='StudentName',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=300,y=80)
        Label(f,text='StudentAge',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=10,y=180)
        Label(f,text='StudentMark',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=300,y=180)
        Label(f,text='StudentMobile',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=10,y=280)
        Label(f,text='StudentDegree',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=300,y=280)
        self.num_1= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.num_1.place(x=10,y=130)
        self.name_1= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.name_1.place(x=300,y=130)
        self.age_1= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.age_1.place(x=10,y=220)
        self.mark_1= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.mark_1.place(x=300,y=220)
        self.mobile_1= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.mobile_1.place(x=10,y=320)
        self.degree_1= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.degree_1.place(x=300,y=320)
        btn_1=Button(f,text='Submit',fg='#17abc2',bg='white',font=('Times New Roman',16,'bold'),padx=20,pady=4,activebackground='#f2da00',cursor='hand2',command=self.add_proces)
        btn_1.place(x=200,y=390)
    def add_proces(self):
        num=self.num_1.get()
        name=self.name_1.get()
        age=self.age_1.get()
        mark=self.mark_1.get()
        mobile=self.mobile_1.get()
        degree=self.degree_1.get()
        qry = 'INSERT INTO stud (num,name,age,mark,mobile,degree) values (%s,%s,%s,%s,%s,%s)'
        tot = (num,name,age,mark,mobile,degree)
        self.cursor.execute(qry,tot)
        self.db.commit()
        messagebox.showinfo('Sucessful','Sucessful ! ! ! !')
    def add_update(self):
        a = self.a
        fr=Frame(a,height=500,width=620,bg='white')
        fr.place(x=250,y=50)
        f = Frame(fr,height=450,width=570,bg='#17abc2')
        f.place(x=25,y=25)
        Label(f,text='ADD STUDENT DETAILS',font=('Times New Roman',30,'bold'),bg='#17abc2',fg='white').place(x=40,y=10)
        Label(f,text='StudentNumber',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=10,y=80)
        Label(f,text='StudentName',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=300,y=80)
        Label(f,text='StudentAge',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=10,y=180)
        Label(f,text='StudentMark',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=300,y=180)
        Label(f,text='StudentMobile',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=10,y=280)
        Label(f,text='StudentDegree',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=300,y=280)
        self.num= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.num.place(x=10,y=130)
        self.name= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.name.place(x=300,y=130)
        self.age= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.age.place(x=10,y=220)
        self.mark= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.mark.place(x=300,y=220)
        self.mobile= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.mobile.place(x=10,y=320)
        self.degree= Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.degree.place(x=300,y=320)
        btn=Button(f,text='Update',fg='#17abc2',bg='white',font=('Times New Roman',16,'bold'),padx=20,pady=4,activebackground='#f2da00',cursor='hand2',command=self.addup_proces)
        btn.place(x=200,y=390)
    def addup_proces(self):
        num=self.num.get()
        name=self.name.get()
        age=self.age.get()
        mark=self.mark.get()
        mobile=self.mobile.get()
        degree=self.degree.get()
        qry = 'UPDATE stud SET name = %s,age= %s,mark= %s,mobile= %s,degree = %s  WHERE num = %s '
        val=(name,age,mark,mobile,degree,num)
        self.cursor.execute(qry,val)
        self.db.commit()
        messagebox.showinfo('Result','Update Successfully ! ')
    def update(self):
        a = self.a
        fr=Frame(a,height=500,width=620,bg='white')
        fr.place(x=250,y=50)
        f = Frame(fr,height=450,width=570,bg='#17abc2')
        f.place(x=25,y=25)
        Label(f,text='UPDATE STUDENT DETAILS',font=('Times New Roman',28,'bold'),bg='#17abc2',fg='white').place(x=34,y=10)
        Label(f,text='StudentNumber',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=10,y=180)
        self.search_num = Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.search_num.place(x=250,y=184)
        btn=Button(f,text='Submit',fg='#17abc2',bg='white',font=('Times New Roman',16,'bold'),padx=20,pady=4,activebackground='#f2da00',cursor='hand2',command=self.update_pro)
        btn.place(x=200,y=250)
    def update_pro(self):
        search=self.search_num.get()
        self.cursor.execute('select * from stud ')
        qry=self.cursor.fetchall()
        for i in qry:
            try:
                if i[0] == int(search):
                    self.add_update()
                    self.num.insert(INSERT,i[0])
                    self.name.insert(INSERT,i[1])
                    self.age.insert(INSERT,i[2])
                    self.mark.insert(INSERT,i[3])
                    self.mobile.insert(INSERT,i[4])
                    self.degree.insert(INSERT,i[5])
            except:
                messagebox.error('error','error')
    def delete(self):
        a = self.a
        fr=Frame(a,height=500,width=620,bg='white')
        fr.place(x=250,y=50)
        f = Frame(fr,height=450,width=570,bg='#17abc2')
        f.place(x=25,y=25)
        Label(f,text='DELETE STUDENT DETAILS',font=('Times New Roman',28,'bold'),bg='#17abc2',fg='white').place(x=34,y=10)
        Label(f,text='StudentNumber',font=('Times New Roman',20,'bold'),bg='#17abc2',fg='white').place(x=10,y=180)
        self.search_delnum = Entry(f,bd=0,font=('Times New Roman',18,'normal'),bg='white',fg='#17abc2',width=17)
        self.search_delnum.place(x=250,y=184)
        btn=Button(f,text='Submit',fg='#17abc2',bg='white',font=('Times New Roman',16,'bold'),padx=20,pady=4,activebackground='#f2da00',cursor='hand2',command=self.del_pro)
        btn.place(x=200,y=250)
    def del_pro(self):
        del_num = self.search_delnum.get()
        qry = "DELETE from stud WHERE num = {} ".format(del_num)
        self.cursor.execute(qry)
        self.db.commit()
        messagebox.showinfo('Result','Deleted Successfully !!!')
    def show(self):
        a = self.a
        fr=Frame(a,height=500,width=620,bg='white')
        fr.place(x=250,y=50)
        t=ttk.Treeview(fr)
        t.place(x=0,y=0,height=600)
        s=Scrollbar(fr,orient='vertical',command=t.yview,bg='white')
        s.place(x=600,y=0,height=500)
        t.configure(xscrollcommand=s.set)
        t['columns']=('1','2','3','4','5','6')
        t['show']='headings'
        t.column('1',width=100)
        t.column('2',width=100)
        t.column('3',width=100)
        t.column('4',width=100)
        t.column('5',width=100)
        t.column('6',width=100)
        t.heading('1',text='StudentID')
        t.heading('2',text='StudentName')
        t.heading('3',text='StudentAge')
        t.heading('4',text='StudentMark')
        t.heading('5',text='StudentMobile')
        t.heading('6',text='StudentDegree')
        self.cursor.execute('SELECT * FROM stud ')
        qry = self.cursor.fetchall()
        for i in qry:
            t.insert('','end',values=(i[0],i[1],i[2],i[3],i[4],i[5]))
            print(i)
    def clear(self):
        a = self.a
        fr=Frame(a,height=500,width=620,bg='white')
        fr.place(x=250,y=50)
        f = Frame(fr,height=450,width=570,bg='#17abc2')
        f.place(x=25,y=25)
        Label(f,text='CLEAR STUDENT PAGE',font=('Times New Roman',30,'bold'),bg='#17abc2',fg='white').place(x=40,y=200)
    def home(self):
        a = self.a
        fr=Frame(a,height=500,width=620,bg='white')
        fr.place(x=250,y=50)
        f = Frame(fr,height=450,width=570,bg='#17abc2')
        f.place(x=25,y=25)
        Label(f,text='WELCOME TO SYSTECH',font=('Times New Roman',30,'bold'),bg='#17abc2',fg='white').place(x=40,y=200)
c=Main()
c.btn()
c.home()
c.a.mainloop()